name: core
description: A new Flutter package project.
version: 0.0.1
homepage: leonardobido.me
publish_to: "none"

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^4.0.4
  dartz: ^0.10.1
  lottie: ^1.1.0
  crypto: ^3.0.1
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  flutter_svg: ^1.0.3
  google_fonts: ^2.3.1
  package_info: ^2.0.2
  firebase_core: ^1.6.0
  flutter_dotenv: ^5.0.2
  webview_flutter: ^3.0.2
  flutter_modular: ^5.0.2
  cupertino_icons: ^1.0.2
  flutter_triple: ^1.2.7+2
  carousel_slider: ^4.0.0
  connectivity_plus: ^2.2.1
  shared_preferences: ^2.0.6
  cached_network_image: ^3.2.0
  flutter_local_notifications: ^9.5.3+1
  syncfusion_flutter_datepicker: ^20.1.55

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
